        
        <form action="/" name="quickquote">
        <table border="0" bgcolor="#B2C492" width="100%">
          <tr>
            <td align="left" class="nav"><b>QSN</b></td>
            <td>&nbsp;</td>
            <td width="20" align="right" class="nav"><a href="index.php">Home</a></td>
            <td width="2" align="right" class="nav">&nbsp;::&nbsp;</td>
            <td width="20" align="right" class="nav"><a href="index.php?act=pend">Pending</a></td>
            <td width="2" align="right" class="nav">&nbsp;::&nbsp;</td>
            <td width="20" align="right" class="nav"><a href="index.php?act=sucks">Marked Sucks</a></td>
            <td width="2" align="right" class="nav">&nbsp;::&nbsp;</td>
            <td width="20" align="right" class="nav"><a href="index.php?act=reje">View Rejects</a></td>
            <td width="2" align="right" class="nav">&nbsp;::&nbsp;</td>            
            <td width="20" align="right" class="nav"><a href="index.php?act=chgpass">Change Password</a></td>
            <td width="2" align="right" class="nav">&nbsp;::&nbsp;</td>            
            <td width="20" align="right" class="nav"><a href="index.php?act=logout">Logout</a></td>            
          </tr>
        </table>
        </form>
        <br />